# Generated by Django 5.1.6 on 2025-03-13 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the team', max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Rider's First name", max_length=20, unique=True)),
                ('last_name', models.CharField(help_text="Rider's Surname", max_length=20, unique=True)),
                ('age', models.PositiveIntegerField(help_text="Rider's age in years.")),
                ('team', models.ForeignKey(help_text='Team the Rider races for', on_delete=django.db.models.deletion.PROTECT, to='world_cup.team')),
            ],
            options={
                'unique_together': {('first_name', 'last_name')},
            },
        ),
    ]
