# Generated by Django 5.1.7 on 2025-03-18 12:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_cup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rider',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterField(
            model_name='rider',
            name='age',
            field=models.PositiveIntegerField(help_text="Rider's age in years", validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='rider',
            name='first_name',
            field=models.CharField(help_text="Rider's first name", max_length=20),
        ),
        migrations.AlterField(
            model_name='rider',
            name='last_name',
            field=models.CharField(help_text="Rider's last name", max_length=20),
        ),
        migrations.AlterField(
            model_name='rider',
            name='team',
            field=models.ForeignKey(help_text='Team the rider races for', on_delete=django.db.models.deletion.PROTECT, related_name='riders', to='world_cup.team'),
        ),
        migrations.CreateModel(
            name='MainRaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish_time', models.DurationField(help_text='Finish time in the main race')),
                ('rider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_race_result', to='world_cup.rider')),
            ],
            options={
                'ordering': ['finish_time'],
            },
        ),
        migrations.CreateModel(
            name='QualifyingRaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifying_time', models.DurationField(help_text='Time taken in the qualifying race')),
                ('rider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qualifying_result', to='world_cup.rider')),
            ],
            options={
                'ordering': ['qualifying_time'],
            },
        ),
    ]
