# Generated by Django 5.1.7 on 2025-03-18 15:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_cup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainraceresult',
            options={'ordering': ['finish_time'], 'verbose_name': 'Main Race Result', 'verbose_name_plural': 'Main Race Results'},
        ),
        migrations.AlterModelOptions(
            name='qualifyingraceresult',
            options={'ordering': ['qualifying_time'], 'verbose_name': 'Qualifying Race Result', 'verbose_name_plural': 'Qualifying Race Results'},
        ),
        migrations.AlterModelOptions(
            name='rider',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Rider', 'verbose_name_plural': 'Riders'},
        ),
        migrations.AlterField(
            model_name='mainraceresult',
            name='finish_time',
            field=models.DurationField(help_text='Finish time in the main race.'),
        ),
        migrations.AlterField(
            model_name='mainraceresult',
            name='rider',
            field=models.OneToOneField(help_text="The rider's main race result.", on_delete=django.db.models.deletion.CASCADE, related_name='main_race_result', to='world_cup.rider'),
        ),
        migrations.AlterField(
            model_name='qualifyingraceresult',
            name='qualifying_time',
            field=models.DurationField(help_text='Time taken in the qualifying race.'),
        ),
        migrations.AlterField(
            model_name='qualifyingraceresult',
            name='rider',
            field=models.OneToOneField(help_text="The rider's qualifying result.", on_delete=django.db.models.deletion.CASCADE, related_name='qualifying_result', to='world_cup.rider'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='age',
            field=models.PositiveIntegerField(help_text="Rider's age in years.", validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='rider',
            name='first_name',
            field=models.CharField(help_text="Rider's first name.", max_length=20),
        ),
        migrations.AlterField(
            model_name='rider',
            name='last_name',
            field=models.CharField(help_text="Rider's last name.", max_length=20),
        ),
        migrations.AlterField(
            model_name='rider',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Optional profile photo of the rider.', null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='race_history',
            field=models.TextField(blank=True, help_text='Optional race history of the rider (e.g., past race results).', null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='team',
            field=models.ForeignKey(help_text='Team the rider races for.', on_delete=django.db.models.deletion.PROTECT, related_name='riders', to='world_cup.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(help_text='Name of the team.', max_length=25, unique=True),
        ),
    ]
